
title: CV
url: 'jeremyjwsc.github.io' 
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Jeremy Williams
tagline: Building blocks upward towards Engineering, Science, Research and Technology
pic: cloud_analytics.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: jeremyjwsc at gmail.com
#phone: XXX-XXX-XXX
website: jeremyjwsc.github.io #do not add http://
#linkedin: jeremyjwsc
#github: jeremyjwsc

#Update all the sections by editing the files inside _includes folder.
